### ISSUE TITLE
it won't load

### ISSUE THREAD

**Issue by earlhsjks** [nulli0n/CoinsEngine-spigot#26]
`[09:38:11] [Server thread/ERROR]: Error occurred while enabling CoinsEngine v2.3.4 (Is it up to date?)
java.lang.NoClassDefFoundError: su/nightexpress/nightcore/command/experimental/argument/ArgumentParser
	at su.nightexpress.coinsengine.command.CommandArguments.currency(CommandArguments.java:23) ~[CoinsEngine-2.3.4.jar:?]
	at su.nightexpress.coinsengine.command.impl.BasicCommands.load(BasicCommands.java:31) ~[CoinsEngine-2.3.4.jar:?]
	at su.nightexpress.coinsengine.CoinsEnginePlugin.registerCommands(CoinsEnginePlugin.java:58) ~[CoinsEngine-2.3.4.jar:?]
	at su.nightexpress.coinsengine.CoinsEnginePlugin.enable(CoinsEnginePlugin.java:34) ~[CoinsEngine-2.3.4.jar:?]
	at su.nightexpress.nightcore.NightPlugin.loadManagers(NightPlugin.java:150) ~[nightcore-2.6.2.jar:?]
	at su.nightexpress.nightcore.NightDataPlugin.loadManagers(NightDataPlugin.java:12) ~[nightcore-2.6.2.jar:?]
	at su.nightexpress.nightcore.NightPlugin.onEnable(NightPlugin.java:56) ~[nightcore-2.6.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: su.nightexpress.nightcore.command.experimental.argument.ArgumentParser
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 17 more`

**Comment by nulli0n** [comment]
https://github.com/nulli0n/nightcore-spigot/releases/tag/v2.6.3-updated
