### ISSUE TITLE
CoinsEngine gives an error and does not start

### ISSUE THREAD

**Issue by isArkaDarkTime** [nulli0n/CoinsEngine-spigot#30]
I use this guide https://nightexpress.gitbook.io/coinsengine/features/cross-server-setup

And here is my code:
```java
if (Bukkit.getPluginManager().getPlugin("CoinsEngine") != null) {
    if (!Bukkit.getPluginManager().isPluginEnabled("CoinsEngine")) {
        ConsoleManager.Console(ConsoleType.WARN, "CoinsEngine is disabled. CoinsEngine economy not supported!", true);
    } else {
        String economyType = config.getString("clans.economy-type");
        if (economyType == null) {
            ConsoleManager.Console(ConsoleType.ERROR, "Economy type not found in config", true);
        }
        if (!economyType.toLowerCase().startsWith("coinsengine")) {
            return;
        }

        String[] parts = economyType.split(";");
        if (parts.length > 1) {
            String currencyName = parts[1].trim();
            if (CoinsEngineAPI.getCurrency(currencyName) == null) {
                ConsoleManager.Console(ConsoleType.ERROR, "Currency \"" + currencyName + "\" not found in your CoinsEngine!", true);
            } else {
                coinsEngineHooked = true;
                ConsoleManager.Console(ConsoleType.INFO, "CoinsEngine found and hooked", true);
            }
        } else {
            ConsoleManager.Console(ConsoleType.ERROR, "Currency name for CoinsEngine is missing in economy-type, example: economy-type: CoinsEngine:currency name", true);
        }
    }
} else {
    ConsoleManager.Console(ConsoleType.WARN, "CoinsEngine not installed, CoinsEngine economy not support!", true);
}
```

In server console:
```[01:26:35 INFO]: [CoinsEngine] Enabling CoinsEngine v2.3.4
[01:26:35 ERROR]: Error occurred while enabling CoinsEngine v2.3.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at su.nightexpress.nightcore.NightPlugin.onEnable(NightPlugin.java:37) ~[CookiesClans-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast arkadarktime.CookiesClans to su.nightexpress.nightcore.NightCore        at java.lang.Class.cast(Class.java:4090) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.getPlugin(JavaPlugin.java:431) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at su.nightexpress.nightcore.util.Plugins.<clinit>(Plugins.java:9) ~[CookiesClans-1.0.jar:?]
        ... 11 more
[01:26:35 INFO]: [CoinsEngine] Disabling CoinsEngine v2.3.4
[01:26:35 ERROR]: Error occurred (in the plugin loader) while disabling CoinsEngine v2.3.4 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class su.nightexpress.nightcore.util.Plugins
        at su.nightexpress.coinsengine.CoinsEnginePlugin.disable(CoinsEnginePlugin.java:63) ~[CoinsEngine-2.3.4.jar:?]
        at su.nightexpress.nightcore.NightPlugin.unloadManagers(NightPlugin.java:159) ~[CookiesClans-1.0.jar:?]
        at su.nightexpress.nightcore.NightDataPlugin.unloadManagers(NightDataPlugin.java:18) ~[CookiesClans-1.0.jar:?]
        at su.nightexpress.nightcore.NightPlugin.onDisable(NightPlugin.java:62) ~[CookiesClans-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ClassCastException: Cannot cast arkadarktime.CookiesClans to su.nightexpress.nightcore.NightCore [in thread "Server thread"]
        at java.lang.Class.cast(Class.java:4090) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.getPlugin(JavaPlugin.java:431) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at su.nightexpress.nightcore.util.Plugins.<clinit>(Plugins.java:9) ~[CookiesClans-1.0.jar:?]
        at su.nightexpress.nightcore.NightPlugin.onEnable(NightPlugin.java:37) ~[CookiesClans-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
        ... 8 more```

**Comment by isArkaDarkTime** [comment]
Hello, i still need help with this error @nulli0n  @NicoNekoDev  @ItzSave  @pedro-dalben, please help with it

**Comment by nulli0n** [comment]
Add CoinsEngine as softdepend

**Comment by isArkaDarkTime** [comment]
> Add CoinsEngine as softdepend

Already add

**Comment by isArkaDarkTime** [comment]
I use in mvn:

Install CoinsEngine
```
install:install-file -Dfile=D:\ArkaDarkTime_CookiesTeam_Projects\MinecraftPlugins\Dependencies\CoinsEngine-2.3.4.jar -DgroupId=su.nightexpress.coinsengine -DartifactId=CoinsEngine -Dversion=2.3.4 -Dpackaging=jar -DgeneratePom=true
```

Install Nightcore
```
install:install-file -Dfile=D:\ArkaDarkTime_CookiesTeam_Projects\MinecraftPlugins\Dependencies\nightcore-2.6.3.jar -DgroupId=su.nightexpress.nightcore -DartifactId=nightcore -Dversion=2.6.3 -Dpackaging=jar -DgeneratePom=true
```
