### ISSUE TITLE
The placeholder color cannot be changed.

### ISSUE THREAD

**Issue by JuraRusan** [nulli0n/CoinsEngine-spigot#32]
Good day!

When using the placeholder, the value always returns with color formatting, which cannot be replaced. Moreover, the color formatting is duplicated. 
```log
... cut log ...
java.util.concurrent.CompletionException: net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
        <#caeaf5>
<#caeaf5>Сервер: <#55ff55>GMGame
<#caeaf5>Пинг: <#55ff55>-1 <#caeaf5>TPS: <#55ff55>20.0 <#caeaf5>Баланс: <#55ff55>§f§f34.51
<#caeaf5>
                                                                                   ^^
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
... cut log ...
```
Configuration example:
```yaml
  footers:
  - |-
    <#caeaf5>
    <#caeaf5>Сервер: <#55ff55>%server%
    <#caeaf5>Пинг: <#55ff55>%ping% <#caeaf5>TPS: <#55ff55>%server_tps_1% <#caeaf5>Баланс: <#55ff55>%coinsengine_balance_gmcoin%
    <#caeaf5>
```

The same issue is also observed when using DeluxeMenus.
```yaml
... cut config ...
      "&#ccb800 * &#caeaf5Ваш баланс: &#55ff55%coinsengine_balance_gmcoin%",
... cut config ...
```
The color I want to apply is not working at all. No matter where I use the placeholder, the output always appears in white.
Could you please remove the color formatting and leave only the number?
For example, currently it is `§f§f34.51`, but I would like it to be just `34.51`.

- `Paper version 1.21.1-40-master@2fdb2e9`
- `CoinsEngine-2.3.4.jar`
- `nightcore-2.6.3.jar`

Thank you very much!

**Comment by nulli0n** [comment]
Added in v2.3.5
