### ISSUE TITLE
CoinsEngine API don't work (will not enable)

### ISSUE THREAD

**Issue by isArkaDarkTime** [nulli0n/CoinsEngine-spigot#34]
Hello! I recreate issue with correctly and detail information.

I use guide: [https://nightexpress.gitbook.io/coinsengine/utility/developer-api](https://nightexpress.gitbook.io/coinsengine/utility/developer-api)

My plugin.yml:
```yaml
name: CookiesClans

version: '${project.version}'

main: arkadarktime.CookiesClans

api-version: '1.19'

authors:
  - ArkaDarkTime
  - Kovarty

description: Simple plugin for clans

softdepend:
  - PlaceholderAPI
  - Vault
  - PlayerPoints
  - CoinsEngine

loadbefore:
  - PlaceholderAPI
  - Vault
  - PlayerPoints
  - CoinsEngine
```

pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>arkadarktime</groupId>
    <artifactId>CookiesClans</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <name>CookiesClans</name>

    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <defaultGoal>clean package</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
        <repository>
            <id>rosewood-repo</id>
            <url>https://repo.rosewooddev.io/repository/public/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>dmulloy2-repo</id>
            <url>https://repo.dmulloy2.net/repository/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.19.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.black_ixx</groupId>
            <artifactId>playerpoints</artifactId>
            <version>3.2.7</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.7.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib</artifactId>
            <version>5.3.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>su.nightexpress.nightcore</groupId>
            <artifactId>nightcore</artifactId>
            <version>2.6.4</version>
        </dependency>
        <dependency>
            <groupId>su.nightexpress.coinsengine</groupId>
            <artifactId>CoinsEngine</artifactId>
            <version>2.3.5</version>
        </dependency>
    </dependencies>
</project>
```

CoinsEngine version: 2.3.5
Nightcore version: 2.6.4

I write this to console:
```cmd
mvn install:install-file -Dfile="D:\ArkaDarkTime_CookiesTeam_Projects\MinecraftPlugins\Dependencies\nightcore-2.6.4.jar" -DgroupId=su.nightexpress.nightcore -DartifactId=nightcore -Dversion=2.6.4 -Dpackaging=jar -DgeneratePom=true
```
```cmd
mvn install:install-file -Dfile="D:\ArkaDarkTime_CookiesTeam_Projects\MinecraftPlugins\Dependencies\CoinsEngine-2.3.5.jar" -DgroupId=su.nightexpress.coinsengine -DartifactId=CoinsEngine -Dversion=2.3.5 -Dpackaging=jar -DgeneratePom=true
```

Error:
```cmd
[20:15:49 INFO]: [CoinsEngine] Enabling CoinsEngine v2.3.5
[20:15:49 ERROR]: Error occurred while enabling CoinsEngine v2.3.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at su.nightexpress.nightcore.NightPlugin.onEnable(NightPlugin.java:36) ~[CookiesClans-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast arkadarktime.CookiesClans to su.nightexpress.nightcore.NightCore
        at java.lang.Class.cast(Class.java:4090) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.getPlugin(JavaPlugin.java:431) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at su.nightexpress.nightcore.util.Plugins.<clinit>(Plugins.java:9) ~[CookiesClans-1.0.jar:?]
        ... 11 more
[20:15:49 INFO]: [CoinsEngine] Disabling CoinsEngine v2.3.5
[20:15:49 ERROR]: Error occurred (in the plugin loader) while disabling CoinsEngine v2.3.5 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class su.nightexpress.nightcore.util.Plugins
        at su.nightexpress.coinsengine.CoinsEnginePlugin.disable(CoinsEnginePlugin.java:63) ~[CoinsEngine-2.3.5.jar:?]
        at su.nightexpress.nightcore.NightPlugin.unloadManagers(NightPlugin.java:168) ~[CookiesClans-1.0.jar:?]
        at su.nightexpress.nightcore.NightDataPlugin.unloadManagers(NightDataPlugin.java:18) ~[CookiesClans-1.0.jar:?]
        at su.nightexpress.coinsengine.CoinsEnginePlugin.unloadManagers(CoinsEnginePlugin.java:71) ~[CoinsEngine-2.3.5.jar:?]
        at su.nightexpress.nightcore.NightPlugin.onDisable(NightPlugin.java:71) ~[CookiesClans-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ClassCastException: Cannot cast arkadarktime.CookiesClans to su.nightexpress.nightcore.NightCore [in thread "Server thread"]
        at java.lang.Class.cast(Class.java:4090) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.getPlugin(JavaPlugin.java:431) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at su.nightexpress.nightcore.util.Plugins.<clinit>(Plugins.java:9) ~[CookiesClans-1.0.jar:?]
        at su.nightexpress.nightcore.NightPlugin.onEnable(NightPlugin.java:36) ~[CookiesClans-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
        ... 8 more
```

**Comment by nulli0n** [comment]
Do not load it before CoinsEngine

**Comment by isArkaDarkTime** [comment]
How can I do this? I already add CoinsEngine to softdepend and loadbefore

**Comment by isArkaDarkTime** [comment]
I have added pom.xml, maybe you need it

**Comment by nulli0n** [comment]
No, remove it from `loadbefore`

**Comment by isArkaDarkTime** [comment]
It helped! Thank you very much!
